### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by vbudilov** [ionic2blueprints/media-player#1]
I'm having a lot of build issues.

At the end of the day, when I run ionic serve, I get the below errors. I'm not seeing the same problems with any other ionic app I have. Any thoughts? 

`EXCEPTION: Error: Uncaught (in promise): ReferenceError: cordova is not defined
browser_adapter.js:77EXCEPTION: Error: Uncaught (in promise): ReferenceError: cordova is not definedBrowserDomAdapter.logError @ browser_adapter.js:77
browser_adapter.js:77STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:77
browser_adapter.js:77Error: Uncaught (in promise): ReferenceError: cordova is not defined
    at resolvePromise (zone.js:418)
    at zone.js:454
    at ZoneDelegate.invokeTask (zone.js:225)
    at Object.onInvokeTask (ng_zone_impl.js:37)
    at ZoneDelegate.invokeTask (zone.js:224)
    at Zone.runTask (zone.js:125)
    at drainMicroTaskQueue (zone.js:357)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:297)BrowserDomAdapter.logError @ browser_adapter.js:77
zone.js:344 Unhandled Promise rejection: cordova is not defined ; Zone: angular ; Task: Promise.then ; Value: ReferenceError: cordova is not defined(…) ReferenceError: cordova is not defined
    at FileProvider.getEntries (http://localhost:8100/build/js/app.bundle.js:446:39)
    at http://localhost:8100/build/js/app.bundle.js:222:22
    at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:192:28)
    at Object.onInvoke (http://localhost:8100/build/js/app.bundle.js:35744:41)
    at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:191:34)
    at Zone.run (http://localhost:8100/build/js/zone.js:85:43)
    at http://localhost:8100/build/js/zone.js:451:57
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/zone.js:225:37)
    at Object.onInvokeTask (http://localhost:8100/build/js/app.bundle.js:35735:41)
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/zone.js:224:42)consoleError @ zone.js:344
zone.js:346 Error: Uncaught (in promise): ReferenceError: cordova is not defined(…)
`

**Comment by imsingh** [comment]
@vbudilov Hi. Since media player uses File Plugin, Media Plugin. You can't use them in Browser. So `ionic serve` won't work and `cordova` is also not available in browser. Run the app on either emulator or device.

**Comment by vbudilov** [comment]
Good to know. thanks! :)
